### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#16]
Light mode toggle switch, largely to be printer-friendly.
(Feature exists in Kirk McDonald calculator)

**Comment by bbarry** [comment]
would a inverse be good enough for the grays or should it be more nuanced?

picturing something like this in styles.scss and getting rid of values,scss in favor of `var(--var-name)` instead of `$var-name`

```scss
$color-white: #fff;
$color-gray-0: #bbb;
$color-gray-1: #333;
$color-gray-2: #2A2A2A;
$color-black: #000;

$color-brand: #ff7200;
$color-back: #171717;
$color-font: #c8c8c8;
$color-invalid: #ff0000;

:root, .dark-mode {
  --color-white: #{$color-white};
  --color-gray-0: #{$color-gray-0};
  --color-gray-1: #{$color-gray-1};
  --color-gray-2: #{$color-gray-2};
  --color-black: #{$color-black};
  
  --color-brand: #{$color-brand};
  --color-back: #{$color-back};
  --color-font: #{$color-font};
  --color-brand: #{$color-invalid};
}

@mixin light-mode {
    --color-white: #{invert($color-white)};
    --color-gray-0: #{invert($color-gray-0)};
    --color-gray-1: #{invert($color-gray-1)};
    --color-gray-2: #{invert($color-gray-2)};
    --color-black: #{invert($color-black)};
    
    --color-back: #{invert($color-back)};
    --color-font: #{invert($color-font)};
}

.light-mode {
  @include light-mode();
}

@media (prefers-color-scheme: light) {
  :root {
    @include light-mode();
  }
}
```

![image](https://user-images.githubusercontent.com/84951/82388709-3baf9500-9a08-11ea-91f1-fdf1621386d0.png)
